Multiplayer data transport
spacesvr/spacesvr pull request #14
Opened 2021-01-14 03:45 UTC by vishaalsc

Streaming position and rotation between peers

2021-01-14 18:25 UTC, alex-shortt requested changes
need to make some clarifications on the pr description of a more concrete goal for this pr. if the goal was to set up data transport system i guess we accomplished it (but then we wouldn't need `Entites.tsx`

But considering how close it is, might as well use this pr to completely wire up the players, just need to pass the received data into the receive function in `Entities.tsx`

2021-01-14 18:25 UTC, alex-shortt commented on src/core/simulated/Entities.tsx
> +
this should be connected

2021-01-14 21:14 UTC, vishaalsc commented on examples/src/scenes/Multiplayer.jsx
> +      disableSimulation={false}
Hm I was almost certain that the default is true - this is what the editor shows, also stops working on my end without the false flag declared there.

![image](https://user-images.githubusercontent.com/14970469/104649845-4ef02e80-5683-11eb-80f4-9e7cddba706c.png)

2021-01-14 21:29 UTC, vishaalsc commented on src/core/utils/hooks.ts
> +  const { simulation } = props;
Since the returned `EnvironmentState` gets its values from `EnvironmentStateProps`, would it be enough just to mark it as optional within the exported type at https://github.com/spacesvr/spacesvr/blob/multiplayer-data-transport/src/core/types/environment.ts#L15 ?

2021-01-14 21:31 UTC, vishaalsc commented on src/core/types/simulation.ts
> +// };
Yeah just laying out the struct. Trying to figure out how to incorporate it and create a data store of player data, that can be shared (updated and transmitted) between peers since there's no central server-based source.

2021-01-15 06:23 UTC, alex-shortt commented on examples/src/scenes/Multiplayer.jsx
> +      disableSimulation={false}
yeah if you pass in a prop with no value it's the equivalent of saying `prop={true}`. when I say defaulting to false, I'm referring to not passing a value for the prop at all

2021-01-15 20:14 UTC, vishaalsc commented on examples/src/scenes/Multiplayer.jsx
> +      disableSimulation={false}
but disableSimulation defaults to true within the type, so not passing it like this means it would never connect? also if it were false by default it it would run on all StandardEnvironment which we don't want, so we actually should pass it like this for the /multiplayer path no?

2021-01-20 02:22 UTC, alex-shortt commented on examples/src/scenes/Multiplayer.jsx
> +      disableSimulation={false}
yes, didn't realize that. usually the standard is to not set a default value for boolean props and word it so that adding the prop sets the idea to true. i.e. naming the prop `disableSimulation` so that, when not passed, the simulation is enabled, but by adding the prop like so: `<Component disableSimulation />`, `disableSimulation` is set to true. 

Fixing in the next commit, only change is not setting a default value for `disableSimluation`

2021-01-20 19:15 UTC, vishaalsc commented on examples/src/scenes/Multiplayer.jsx
> +      disableSimulation={false}
I see - so I guess now everywhere `StandardEnvironment` is used, there would have to be a `disableSimulation` attribute as part of the tag? Ergo, only place where the prop wouldn't be passed in is in Multiplayer.jsx's `<StandardEnvironment>`?

2021-01-22 01:01 UTC, alex-shortt approved these changes

2021-01-22 01:01 UTC, merged