Signalling with Beanstalk and small fixes
spacesvr/spacesvr pull request #21
Opened 2021-03-13 01:58 UTC by vishaalsc

Replaced `disableSimulation` flag from `<StandardEnvironment>` with `simulationProps` to opt-in vs opt-out. Added some extra code and comments to _simulation.ts_, and some minor structure edits to _app.js_.

2021-03-13 02:36 UTC, alex-shortt requested changes

2021-03-13 02:36 UTC, alex-shortt commented on src/core/environments/StandardEnvironment.tsx
> +  const simulation = useSimulationState({ ...simulationProps });
can be simplified to `useSimulationState(simulationProps)`

2021-03-13 02:36 UTC, alex-shortt commented on src/core/utils/simulation.ts
> +  }, [peer]);
add `props` to the dependency array

2021-03-13 06:04 UTC, vishaalsc commented on src/core/environments/StandardEnvironment.tsx
> +  const simulation = useSimulationState({ ...simulationProps });
that gives me an error, since `simulationProps` is type `SimulationProps | undefined` as an optional param. I can assert non-null with `simulationProps!`, but maybe we should keep it this way?

2021-03-15 10:14 UTC, alex-shortt commented on src/core/environments/StandardEnvironment.tsx
> +  const simulation = useSimulationState({ ...simulationProps });
you can also make the props for `useSimulationState` optional so that its type is also `SimulationProps | undefined`, and considering that you're checking whether props exist inside of `simulation.ts` as a means of checking whether the end user wants to enable the simulation, it makes sense that the value could be undefined.

2021-03-15 17:30 UTC, vishaalsc commented on src/core/environments/StandardEnvironment.tsx
> +  const simulation = useSimulationState({ ...simulationProps });
Okay cool, TS doesn't seem to like the second option since the props won't exist on `Simulation | undefined` but that's probably fine since we're checking in the connection process like you said

2021-03-15 17:37 UTC, vishaalsc commented
Wait looks like making that change to `useSimulationState` broke the env, reverting

2021-03-19 18:22 UTC, alex-shortt approved these changes

2021-03-19 18:22 UTC, merged