Add basic VR movement for Oculus Quest
spacesvr/spacesvr pull request #3
Opened 2020-11-20 11:25 UTC by hitchcott

This PR adds support for oculus quest to the `StandardEnvironment`, enabled with the `vr` property, which is enabled in the example. Not enabling `vr` keeps the environment as it was before, using the regular canvas and movement. 

I've tried to follow the project structure by adding `VRController` and `VRControllerMovement` components. 

Users can look around in VR and move around using the control sticks on the oculus quest. Right now it is just basic movement on a plane but perhaps this can be extended in the future to include alternative movement methods such as flying or teleport movement.

The VR flag disables effects as they seem to break VR mode. Perhaps there's a specific effect causing this, but for now I've just disabled them all.

I had to wrap the camera inside a group that was attached to the player object in order to allow the camera to have a base rotation as well as the rotation from head movement, and I pass this down to the VR component to rotate.

If you have any suggestions for better ways to implement this, I'm happy to contribute further. Otherwise, I hope this serves as a reference for implementing VR support and I will continue testing this implementation.

2020-11-21 03:26 UTC, hitchcott commented on src/core/controls/VRControls.tsx
> +  camParent: any;
This type needs updating.

Should I be using `RefObject<Group>` or `MutableRefObject<Group>` ?

2020-11-23 05:55 UTC, hitchcott commented
While the logic for movement I think works well, I think the `vr` flag should probably re-considered and maybe made default, otherwise there are unsightly checks for `vr` dotted around. Thoughts?

2020-11-23 22:26 UTC, alex-shortt commented
sorry should be able to get to it tonight, but yes i agree, vr should be the default. as such, components that add functionality that would interface with vr (such as the `Interactable` modifier) would know to handle the vr vs. non-vr case.

2020-11-24 00:22 UTC, alex-shortt requested changes
I'm assuming there's no downside to enabling a vr canvas by default (although the post processing effects line might negate that completely), but if there aren't it should be enabled by default

In general deploying to all 3 platforms at once with no decision to be made would be ideal

2020-11-24 00:22 UTC, alex-shortt commented on src/core/players/Player.tsx
> +        {vr && (
seems like camParent ref can be handled by VRControls component

2020-11-24 00:22 UTC, alex-shortt commented on examples/src/App.jsx
> +      vr
don't need a flag, vr should be enabled by default

2020-11-24 00:22 UTC, alex-shortt commented on src/core/controls/VRControllerMovement.tsx
> +      );
rotation works, but movement doesn't seem to be working for me. any idea why this would be happening?

2020-11-24 00:22 UTC, alex-shortt commented on src/core/controls/VRControls.tsx
> +    </>
remove fragments

2020-11-24 00:22 UTC, alex-shortt commented on src/core/environments/StandardEnvironment.tsx
> +  const Canvas = vr ? VRCanvas : RegularCanvas;
vr flag will be true by default, so i guess we're only using the `VRCanavas` component

2020-11-24 00:22 UTC, alex-shortt commented on src/core/environments/StandardEnvironment.tsx
> +          {vr && <DefaultXRControllers />}
don't need vr flag

2020-11-24 00:22 UTC, alex-shortt commented on src/core/environments/StandardEnvironment.tsx
> +              {effects || (!vr && <RealisticEffects />)}
can you not have post processing effects with vr?

2020-11-24 00:22 UTC, alex-shortt commented on src/core/environments/StandardEnvironment.tsx
> +              <Player initPos={player?.pos} initRot={player?.rot} vr={vr} />
don't need vr flag

2020-11-24 00:22 UTC, alex-shortt commented on src/core/players/Player.tsx
> +  vr?: boolean;
don't need vr flag

2020-11-24 00:22 UTC, alex-shortt commented on src/core/players/Player.tsx
> +
seems like camParent ref can be handled by `VRControls` component

2020-11-24 00:22 UTC, alex-shortt commented on src/core/players/Player.tsx
> +      {vr && (
don't need vr flag

2021-04-13 07:28 UTC, alex-shortt commented
copied some of the code to #24, closing now

2021-04-13 07:28 UTC, closed without merging