Ia ktx
spacesvr/spacesvr pull request #40
Opened 2021-05-14 02:05 UTC by ianyimi

ktx2 support for images only

2021-05-14 18:09 UTC, alex-shortt requested changes

2021-05-14 18:09 UTC, alex-shortt commented on examples/src/scenes/Starter.jsx
> +  // }, []);
comments

2021-05-14 18:09 UTC, alex-shortt commented on src/components/Image.tsx
> +  const ktx = src.includes(".ktx2");
`isKtx` would be more clear

2021-05-14 18:09 UTC, alex-shortt commented on src/components/Image.tsx
> +    (loader: KTX2Loader) => {
you should cast it to a `KTX2Loader` when you go to use it on lines 8-32 as at this point you don't know which is which

2021-05-14 18:09 UTC, alex-shortt commented on src/components/Image.tsx
> +        console.log(src);
remove console log

2021-05-14 18:09 UTC, alex-shortt commented on src/components/Image.tsx
> +      <mesh rotation-x={ktx ? Math.PI : 0}>
really? ktx flips it?

2021-05-14 18:09 UTC, alex-shortt commented on src/core/environments/StandardEnvironment.tsx
> +  signup?: string;
signup code should not be mixed in with the ktx pr

2021-05-14 18:09 UTC, alex-shortt commented on src/core/overlays/DesktopPause.tsx
> +  font-size: 0.5em;
signup code should not be mixed in with the ktx pr

2021-05-14 18:09 UTC, alex-shortt commented on src/core/overlays/DesktopPause.tsx
> +        {signup && (
signup code should not be mixed in with the ktx pr

2021-05-19 02:11 UTC, ianyimi commented on src/components/Image.tsx
> +      <mesh rotation-x={ktx ? Math.PI : 0}>
yeah im not sure why

2021-05-20 03:29 UTC, alex-shortt commented on src/components/Image.tsx
> +  }
really not a fan of this solution as it requires an extra file to be created and kept track of. 

i'll allow it for now but submit an issue to fix it after it's merged

2021-05-20 03:29 UTC, alex-shortt commented on src/components/misc/Frame.tsx
> +  const borderDepth = 0.08;
this is where it's becoming obvious that we need better examples .... this is a pretty drastic change (3x, 1.6x) so i think it would break a lot of the images we're currently shipping, no?

2021-05-20 03:58 UTC, ianyimi commented on src/components/misc/Frame.tsx
> +  const borderDepth = 0.08;
I dont think these values are affected by the any scaling. eveything looks fine when I copied in an image scaled 12x

2021-05-20 04:33 UTC, merged