Multinational Keyboard Support
spacesvr/spacesvr pull request #51
Opened 2021-06-06 12:54 UTC by AlaricBaraou

Multinational Keyboard Support 
issue #32 

As discussed in the issue, here is my proposition for handling this.

For all browsers supporting event.code we use it as it's the optimal way to handle this.
But I kept the ev.key and ev.keyCode from the example as fallback for older browsers. 

I also added some code in DesktopPause.tsx to display ZDSQ instead of WASD when opened from a browser that support the [Keyboard_API](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard_API) ( chrome, edge, opera ) and use an Azerty Keyboard.

So currently, on "all" keyboard it's possible to use the keys located in this two red areas and also the num pad or the arrow keys.
![CaptureKeyboard](https://user-images.githubusercontent.com/7174039/120925030-dee85080-c6d6-11eb-90fa-87ed64bf27df.PNG)

I personally think it's great like this but we can remove some of the code that you think is unescessary of course.

Let me know if I need to clarify some of my choices.

2021-06-08 00:38 UTC, alex-shortt requested changes

2021-06-08 00:38 UTC, alex-shortt commented on src/core/overlays/DesktopPause.tsx
> +  }
seems like this might be good to be moved to a separate hook in `core/utils`, thinking something like

```
const layout = useKeyboardLayout()
```

and having all this run in a `useEffect`. dont forsee this result changing at any point during the user's session

2021-06-08 17:10 UTC, AlaricBaraou commented on src/core/overlays/DesktopPause.tsx
> +  }
Thanks for the feedback, I updated it, let me know what you think.

2021-06-17 04:10 UTC, alex-shortt approved these changes

2021-06-17 04:10 UTC, merged